inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - tmp/**/*
    - lib/bundler/vendor/**/*
  DisplayCopNames: true

# Lint

Lint/EndAlignment:
  AlignWith: variable
  AutoCorrect: true

# Style

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# We adopted raise instead of fail.
Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Having these make it easier to *not* forget to add one when adding a new
# value and you can simply copy the previous line.
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# 1.8.7 support

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/DotPosition:
  EnforcedStyle: trailing
