sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install bundler -v 1.12.5
  - cp .token.yml.example .token.yml
  - echo -e "token:\n  $GITHUB_TOKEN" > ./.token.yml
script:
  - RAILS_ENV=test bundle exec rspec
  - bundle exec rubocop
